# Generated by Django 5.0.6 on 2024-07-02 05:41

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    building = apps.get_model('GeoApp', 'Building')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    addr = tags.get('addr:street', 'Unknown') + ' ' + tags.get('addr:housenumber', '')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    building(address=addr, geom=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('GeoApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]


